
package com.raul.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoWS", targetNamespace = "http://ws.raul.com/", wsdlLocation = "http://localhost:8080/JAX-WS-RM-01_Server/echo?wsdl")
public class EchoWS_Service
    extends Service
{

    private final static URL ECHOWS_WSDL_LOCATION;
    private final static WebServiceException ECHOWS_EXCEPTION;
    private final static QName ECHOWS_QNAME = new QName("http://ws.raul.com/", "EchoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JAX-WS-RM-01_Server/echo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOWS_WSDL_LOCATION = url;
        ECHOWS_EXCEPTION = e;
    }

    public EchoWS_Service() {
        super(__getWsdlLocation(), ECHOWS_QNAME);
    }

    public EchoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOWS_QNAME, features);
    }

    public EchoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, ECHOWS_QNAME);
    }

    public EchoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOWS_QNAME, features);
    }

    public EchoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoWS
     */
    @WebEndpoint(name = "EchoWSPort")
    public EchoWS getEchoWSPort() {
        return super.getPort(new QName("http://ws.raul.com/", "EchoWSPort"), EchoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoWS
     */
    @WebEndpoint(name = "EchoWSPort")
    public EchoWS getEchoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.raul.com/", "EchoWSPort"), EchoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOWS_EXCEPTION!= null) {
            throw ECHOWS_EXCEPTION;
        }
        return ECHOWS_WSDL_LOCATION;
    }

}
